import { Target, Search, Users, Megaphone, Code, BarChart3, TrendingUp, LucideIcon } from 'lucide-react'

export interface Service {
  slug: string
  icon: LucideIcon
  title: string
  description: string
  longDescription: string
  features: string[]
  benefits: string[]
  process: string[]
  tools: string[]
  color: string
  pricing: string
}

export const servicesData: Service[] = [
  {
    slug: 'digital-marketing-strategy',
    icon: Target,
    title: 'Digital Marketing Strategy',
    description: 'Comprehensive digital marketing strategies tailored to your business goals.',
    longDescription: 'I develop data-driven digital marketing strategies that align with your business objectives and deliver measurable results. From brand positioning to multi-channel campaigns, I help you build a cohesive digital presence that resonates with your target audience and drives growth.',
    features: [
      'Digital audits & brand positioning',
      'Content strategy development',
      'Platform selection & analysis',
      'Competitor analysis',
      'Growth roadmap creation',
      'KPI definition & tracking',
    ],
    benefits: [
      'Clear roadmap for digital growth',
      'Better ROI on marketing spend',
      'Aligned team and stakeholders',
      'Data-driven decision making',
      'Competitive market advantage',
    ],
    process: [
      'Discovery & goal setting',
      'Market & competitor research',
      'Strategy development',
      'Implementation planning',
      'Execution & monitoring',
      'Optimization & reporting',
    ],
    tools: ['Google Analytics', 'SEMrush', 'Ahrefs', 'HubSpot', 'Miro'],
    color: 'from-secondary to-secondary-600',
    pricing: 'Starting from $500/month',
  },
  {
    slug: 'seo-ai-search-optimization',
    icon: Search,
    title: 'SEO & AI Search Optimization',
    description: 'Get found online with cutting-edge SEO and AI search optimization strategies.',
    longDescription: 'I optimize your website for both traditional search engines and AI-powered search platforms like ChatGPT and Google SGE. My approach combines technical SEO, content optimization, and emerging AI search strategies to ensure your brand gets discovered by your target audience.',
    features: [
      'Comprehensive website audits',
      'Technical SEO fixes',
      'Content optimization',
      'AI search optimization (SGE, ChatGPT)',
      'Keyword & ranking strategy',
      'Blog content planning',
      'Link building strategy',
    ],
    benefits: [
      '75%+ organic traffic growth',
      'Higher search engine rankings',
      'Improved website authority',
      'Better user experience',
      'Long-term sustainable growth',
    ],
    process: [
      'SEO audit & analysis',
      'Technical fixes implementation',
      'Keyword research & planning',
      'Content optimization',
      'AI search optimization',
      'Ongoing monitoring & reporting',
    ],
    tools: ['Google Search Console', 'SEMrush', 'Screaming Frog', 'Ahrefs', 'RankMath'],
    color: 'from-accent to-accent-600',
    pricing: 'Starting from $800/month',
  },
  {
    slug: 'social-media-management',
    icon: Users,
    title: 'Social Media Management & Content Creation',
    description: 'Build your brand presence with engaging content and strategic social media management.',
    longDescription: 'I create and manage authentic social media content that builds community, drives engagement, and converts followers into customers. From strategy to execution, I handle everything needed to grow your brand on social platforms.',
    features: [
      'Content calendar creation',
      'Professional photography & videography',
      'Reels & short-form videos',
      'Caption writing & scheduling',
      'Community management',
      'Performance tracking',
      'Influencer collaborations',
    ],
    benefits: [
      '3M+ profile views generated',
      '60%+ engagement rate increase',
      'Viral content strategies',
      'Authentic community building',
      'Consistent brand voice',
    ],
    process: [
      'Brand audit & strategy',
      'Content planning & calendar',
      'Content creation & editing',
      'Posting & scheduling',
      'Community engagement',
      'Analytics & optimization',
    ],
    tools: ['Meta Business Suite', 'Canva', 'CapCut Pro', 'Later', 'Hootsuite'],
    color: 'from-secondary to-accent',
    pricing: 'Starting from $600/month',
  },
  {
    slug: 'paid-media-advertising',
    icon: Megaphone,
    title: 'Paid Media (Google Ads, Meta Ads)',
    description: 'Drive targeted traffic and conversions with data-driven paid advertising campaigns.',
    longDescription: 'I design and manage high-performance paid advertising campaigns that deliver measurable ROI. My data-driven approach combines strategic targeting, compelling ad creative, and continuous optimization to maximize your advertising budget.',
    features: [
      'Campaign strategy & setup',
      'Ad creative development',
      'Audience targeting & segmentation',
      'A/B testing & optimization',
      'ROAS tracking & reporting',
      'Budget management',
      'Conversion tracking setup',
    ],
    benefits: [
      '5X ROAS achieved',
      'Lower cost per acquisition',
      'Precise audience targeting',
      'Scalable campaigns',
      'Real-time performance insights',
    ],
    process: [
      'Campaign goal setting',
      'Audience research & targeting',
      'Ad creative development',
      'Campaign launch',
      'Performance monitoring',
      'Optimization & scaling',
    ],
    tools: ['Google Ads', 'Meta Ads Manager', 'Google Tag Manager', 'GA4', 'Looker Studio'],
    color: 'from-secondary-600 to-primary',
    pricing: 'Starting from $700/month + ad spend',
  },
  {
    slug: 'web-design-development',
    icon: Code,
    title: 'Web Design & Development',
    description: 'Modern, conversion-focused websites that elevate your brand and drive results.',
    longDescription: 'I build beautiful, fast, and conversion-optimized websites that work seamlessly across all devices. Using modern technologies and best practices, I create web experiences that not only look great but also drive business results.',
    features: [
      'Custom website design (UI/UX)',
      'Responsive development',
      'E-commerce solutions',
      'Landing page optimization',
      'Website maintenance',
      'Performance optimization',
      'SEO-friendly architecture',
    ],
    benefits: [
      '50%+ conversion rate increase',
      'Fast loading speeds',
      'Mobile-optimized experience',
      'Modern, professional design',
      'Easy content management',
    ],
    process: [
      'Discovery & planning',
      'Design & wireframing',
      'Development & testing',
      'Content integration',
      'Launch & optimization',
      'Ongoing support',
    ],
    tools: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'WordPress', 'Webflow'],
    color: 'from-accent to-secondary',
    pricing: 'Starting from $2,000 per project',
  },
  {
    slug: 'data-analytics-reporting',
    icon: BarChart3,
    title: 'Data Analytics & Reporting',
    description: 'Turn data into actionable insights with comprehensive analytics and reporting.',
    longDescription: 'I set up and manage analytics systems that provide clear insights into your marketing performance. From tracking setup to custom dashboards, I help you understand what is working and make data-driven decisions to optimize your marketing efforts.',
    features: [
      'GA4 setup & configuration',
      'Custom dashboard creation',
      'Performance tracking',
      'Conversion rate optimization',
      'ROI analysis',
      'Monthly reporting',
      'Data visualization',
    ],
    benefits: [
      'Clear performance insights',
      'Better decision making',
      'Track what matters',
      'Identify optimization opportunities',
      'Prove marketing ROI',
    ],
    process: [
      'Analytics audit',
      'Tracking implementation',
      'Dashboard setup',
      'Data collection & monitoring',
      'Analysis & insights',
      'Regular reporting',
    ],
    tools: ['Google Analytics 4', 'Power BI', 'Looker Studio', 'Excel', 'Python'],
    color: 'from-primary to-accent-600',
    pricing: 'Starting from $400/month',
  },
  {
    slug: 'brand-strategy-consulting',
    icon: TrendingUp,
    title: 'Brand Strategy & Digital Growth Consulting',
    description: 'Premium consulting to define your digital roadmap and accelerate sustainable growth.',
    longDescription: 'I provide strategic guidance to help businesses define their brand positioning, develop growth strategies, and navigate digital transformation. Through workshops, advisory sessions, and hands-on implementation support, I help you build a sustainable competitive advantage.',
    features: [
      'Brand positioning & messaging',
      'Digital transformation strategy',
      'Multi-channel marketing plans',
      'Team training & workshops',
      'Strategic advisory',
      'Growth experimentation',
      'Market analysis',
    ],
    benefits: [
      'Clear brand differentiation',
      'Aligned team & stakeholders',
      'Sustainable growth framework',
      'Competitive market advantage',
      'Strategic clarity',
    ],
    process: [
      'Business assessment',
      'Strategy development',
      'Workshop & training',
      'Implementation planning',
      'Ongoing advisory',
      'Performance review',
    ],
    tools: ['Strategic Frameworks', 'Market Research Tools', 'Analytics Platforms', 'Miro', 'Notion'],
    color: 'from-secondary to-primary-700',
    pricing: 'Starting from $1,500/month',
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return servicesData.find((service) => service.slug === slug)
}
